//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Battle.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Army
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Army()
        {
            this.Battlemechs = new HashSet<Battlemech>();
        }
    
        public int rid { get; set; }
        public Nullable<int> id { get; set; }
        public string name { get; set; }
        public Nullable<int> ridcountry { get; set; }
        public Nullable<int> ridgamer { get; set; }
        public int UserId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Gamer Gamer { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Battlemech> Battlemechs { get; set; }
    }
}
