//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Battle.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryInit
    {
        public int rid { get; set; }
        public Nullable<int> id { get; set; }
        public string cod { get; set; }
        public string nameRus { get; set; }
        public string color { get; set; }
        public Nullable<int> population { get; set; }
        public Nullable<int> mineral { get; set; }
        public Nullable<int> ridgamer { get; set; }
        public Nullable<int> populationreal { get; set; }
        public string nameEng { get; set; }
    }
}
