//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Battle.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Country()
        {
            this.Armies = new HashSet<Army>();
            this.Manufactures = new HashSet<Manufacture>();
            this.Evs = new HashSet<Ev>();
        }
    
        public int rid { get; set; }
        public Nullable<int> id { get; set; }
        public string cod { get; set; }
        public string nameRus { get; set; }
        public string nameEng { get; set; }
        public string color { get; set; }
        public Nullable<int> population { get; set; }
        public Nullable<int> mineral { get; set; }
        public Nullable<int> ridgamer { get; set; }
        public Nullable<int> populationreal { get; set; }
        public int UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Army> Armies { get; set; }
        public virtual Gamer Gamer { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manufacture> Manufactures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ev> Evs { get; set; }
    }
}
