//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Battle.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Design
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Design()
        {
            this.Battlemechs = new HashSet<Battlemech>();
            this.Manufactures = new HashSet<Manufacture>();
        }
    
        public int rid { get; set; }
        public Nullable<int> id { get; set; }
        public string name { get; set; }
        public Nullable<int> shield { get; set; }
        public Nullable<int> guns { get; set; }
        public Nullable<int> caliber { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<int> ridgamer { get; set; }
        public Nullable<int> UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Battlemech> Battlemechs { get; set; }
        public virtual Gamer Gamer { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manufacture> Manufactures { get; set; }
    }
}
