//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Battle.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ev
    {
        public int id { get; set; }
        public string message { get; set; }
        public Nullable<int> ridcountry { get; set; }
        public Nullable<int> ridgamer { get; set; }
        public Nullable<int> turn { get; set; }
        public int UserId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Gamer Gamer { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
